create_clock -period 20.000 -name sys_clk_50m -waveform {0.000 10.000} [get_ports clk_in1_0]

set_clock_groups -name clk_group_64m -asynchronous -group [get_clocks [get_clocks -of_objects [get_pins xsdr_design_1_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]]]
set_clock_groups -name clk_group_100m -asynchronous -group [get_clocks [get_clocks -of_objects [get_pins xsdr_design_1_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]]]

set_property PACKAGE_PIN N14 [get_ports clk_in1_0]
set_property IOSTANDARD LVTTL [get_ports clk_in1_0]
set_property PACKAGE_PIN B2 [get_ports clk_out1_0]
set_property IOSTANDARD LVTTL [get_ports clk_out1_0]
set_property PACKAGE_PIN J3 [get_ports resetn_0]
set_property IOSTANDARD LVTTL [get_ports resetn_0]

set_property PACKAGE_PIN B7 [get_ports {adc_data_in_0[11]}]
set_property PACKAGE_PIN D5 [get_ports {adc_data_in_0[10]}]
set_property PACKAGE_PIN D6 [get_ports {adc_data_in_0[9]}]
set_property PACKAGE_PIN B5 [get_ports {adc_data_in_0[8]}]
set_property PACKAGE_PIN B6 [get_ports {adc_data_in_0[7]}]
set_property PACKAGE_PIN C6 [get_ports {adc_data_in_0[6]}]
set_property PACKAGE_PIN C7 [get_ports {adc_data_in_0[5]}]
set_property PACKAGE_PIN A4 [get_ports {adc_data_in_0[4]}]
set_property PACKAGE_PIN A5 [get_ports {adc_data_in_0[3]}]
set_property PACKAGE_PIN A3 [get_ports {adc_data_in_0[2]}]
set_property PACKAGE_PIN B4 [get_ports {adc_data_in_0[1]}]
set_property PACKAGE_PIN A2 [get_ports {adc_data_in_0[0]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[11]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[10]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[9]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[8]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[7]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[6]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[5]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[4]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[3]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[2]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[1]}]
set_property IOSTANDARD LVTTL [get_ports {adc_data_in_0[0]}]

set_property PACKAGE_PIN M4 [get_ports adc_otr_led_0]
set_property IOSTANDARD LVTTL [get_ports adc_otr_led_0]
set_property PACKAGE_PIN N3 [get_ports clken_led_0]
set_property IOSTANDARD LVTTL [get_ports clken_led_0]
set_property PACKAGE_PIN A7 [get_ports adc_otr_in_0]
set_property IOSTANDARD LVTTL [get_ports adc_otr_in_0]
set_property IOSTANDARD LVTTL [get_ports fifo_full_led_0]
set_property PACKAGE_PIN L4 [get_ports fifo_full_led_0]

set_property PACKAGE_PIN P9 [get_ports fx3_flaga_0]
set_property IOSTANDARD LVTTL [get_ports fx3_flaga_0]
set_property PACKAGE_PIN P10 [get_ports fx3_flagb_0]
set_property IOSTANDARD LVTTL [get_ports fx3_flagb_0]
set_property PACKAGE_PIN P8 [get_ports fx3_flagc_0]
set_property IOSTANDARD LVTTL [get_ports fx3_flagc_0]
set_property PACKAGE_PIN K12 [get_ports fx3_flagd_0]
set_property IOSTANDARD LVTTL [get_ports fx3_flagd_0]

set_property PACKAGE_PIN N11 [get_ports fx3_pclk_0]
set_property IOSTANDARD LVTTL [get_ports fx3_pclk_0]
set_property PACKAGE_PIN N2 [get_ports fx3_reset_0]
set_property IOSTANDARD LVTTL [get_ports fx3_reset_0]

set_property PACKAGE_PIN T10 [get_ports fx3_slwr_0]
set_property IOSTANDARD LVTTL [get_ports fx3_slwr_0]
set_property PULLUP true [get_ports fx3_slwr_0]
set_property PACKAGE_PIN P6 [get_ports fx3_slrd_0]
set_property IOSTANDARD LVTTL [get_ports fx3_slrd_0]
set_property PULLUP true [get_ports fx3_slrd_0]
set_property PACKAGE_PIN R10 [get_ports fx3_sloe_0]
set_property IOSTANDARD LVTTL [get_ports fx3_sloe_0]
set_property PULLUP true [get_ports fx3_sloe_0]
set_property PACKAGE_PIN T9 [get_ports fx3_slcs_0]
set_property IOSTANDARD LVTTL [get_ports fx3_slcs_0]
set_property PULLUP true [get_ports fx3_slcs_0]
set_property PACKAGE_PIN M6 [get_ports fx3_pktend_0]
set_property IOSTANDARD LVTTL [get_ports fx3_pktend_0]
set_property PULLUP true [get_ports fx3_pktend_0]

set_property PACKAGE_PIN R11 [get_ports {fx3_a_0[1]}]
set_property PACKAGE_PIN K13 [get_ports {fx3_a_0[0]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_a_0[1]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_a_0[0]}]

set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[31]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[30]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[29]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[28]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[27]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[26]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[25]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[24]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[23]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[22]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[21]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[20]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[19]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[18]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[17]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[16]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[15]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[14]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[13]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[12]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[11]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[10]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[9]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[8]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[7]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[6]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[5]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[4]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[3]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[2]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[1]}]
set_property IOSTANDARD LVTTL [get_ports {fx3_dq_0[0]}]
set_property PACKAGE_PIN P15 [get_ports {fx3_dq_0[31]}]
set_property PACKAGE_PIN N13 [get_ports {fx3_dq_0[30]}]
set_property PACKAGE_PIN P16 [get_ports {fx3_dq_0[29]}]
set_property PACKAGE_PIN P13 [get_ports {fx3_dq_0[28]}]
set_property PACKAGE_PIN R16 [get_ports {fx3_dq_0[27]}]
set_property PACKAGE_PIN P11 [get_ports {fx3_dq_0[26]}]
set_property PACKAGE_PIN R15 [get_ports {fx3_dq_0[25]}]
set_property PACKAGE_PIN M12 [get_ports {fx3_dq_0[24]}]
set_property PACKAGE_PIN T14 [get_ports {fx3_dq_0[23]}]
set_property PACKAGE_PIN T15 [get_ports {fx3_dq_0[22]}]
set_property PACKAGE_PIN P14 [get_ports {fx3_dq_0[21]}]
set_property PACKAGE_PIN T12 [get_ports {fx3_dq_0[20]}]
set_property PACKAGE_PIN T13 [get_ports {fx3_dq_0[19]}]
set_property PACKAGE_PIN R13 [get_ports {fx3_dq_0[18]}]
set_property PACKAGE_PIN N12 [get_ports {fx3_dq_0[17]}]
set_property PACKAGE_PIN R12 [get_ports {fx3_dq_0[16]}]
set_property PACKAGE_PIN N6 [get_ports {fx3_dq_0[15]}]
set_property PACKAGE_PIN P5 [get_ports {fx3_dq_0[14]}]
set_property PACKAGE_PIN T8 [get_ports {fx3_dq_0[13]}]
set_property PACKAGE_PIN T7 [get_ports {fx3_dq_0[12]}]
set_property PACKAGE_PIN R8 [get_ports {fx3_dq_0[11]}]
set_property PACKAGE_PIN R6 [get_ports {fx3_dq_0[10]}]
set_property PACKAGE_PIN R7 [get_ports {fx3_dq_0[9]}]
set_property PACKAGE_PIN T5 [get_ports {fx3_dq_0[8]}]
set_property PACKAGE_PIN N4 [get_ports {fx3_dq_0[7]}]
set_property PACKAGE_PIN R5 [get_ports {fx3_dq_0[6]}]
set_property PACKAGE_PIN M5 [get_ports {fx3_dq_0[5]}]
set_property PACKAGE_PIN P4 [get_ports {fx3_dq_0[4]}]
set_property PACKAGE_PIN T4 [get_ports {fx3_dq_0[3]}]
set_property PACKAGE_PIN L5 [get_ports {fx3_dq_0[2]}]
set_property PACKAGE_PIN P3 [get_ports {fx3_dq_0[1]}]
set_property PACKAGE_PIN T3 [get_ports {fx3_dq_0[0]}]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
