# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xsdr_constr_1.xdc

# Block Designs: bd/xsdr_design_1/xsdr_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1 || ORIG_REF_NAME==xsdr_design_1} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_clk_wiz_0_0 || ORIG_REF_NAME==xsdr_design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_ad9226_ibuf_0_0/xsdr_design_1_ad9226_ibuf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_ad9226_ibuf_0_0 || ORIG_REF_NAME==xsdr_design_1_ad9226_ibuf_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_dds_compiler_0_0/xsdr_design_1_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_dds_compiler_0_0 || ORIG_REF_NAME==xsdr_design_1_dds_compiler_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_dds_axis_data_to_sin_0_0/xsdr_design_1_dds_axis_data_to_sin_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_dds_axis_data_to_sin_0_0 || ORIG_REF_NAME==xsdr_design_1_dds_axis_data_to_sin_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_mult_gen_0_0/xsdr_design_1_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_mult_gen_0_0 || ORIG_REF_NAME==xsdr_design_1_mult_gen_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_mult_gen_1_0/xsdr_design_1_mult_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_mult_gen_1_0 || ORIG_REF_NAME==xsdr_design_1_mult_gen_1_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_cic_compiler_0_0/xsdr_design_1_cic_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_cic_compiler_0_0 || ORIG_REF_NAME==xsdr_design_1_cic_compiler_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_cic_compiler_1_0/xsdr_design_1_cic_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_cic_compiler_1_0 || ORIG_REF_NAME==xsdr_design_1_cic_compiler_1_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_fir_compiler_0_0/xsdr_design_1_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_fir_compiler_0_0 || ORIG_REF_NAME==xsdr_design_1_fir_compiler_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_fir_compiler_1_0/xsdr_design_1_fir_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_fir_compiler_1_0 || ORIG_REF_NAME==xsdr_design_1_fir_compiler_1_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_iq32_to_fifo32_0_1/xsdr_design_1_iq32_to_fifo32_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_iq32_to_fifo32_0_1 || ORIG_REF_NAME==xsdr_design_1_iq32_to_fifo32_0_1} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_0_0/xsdr_design_1_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_fifo_generator_0_0 || ORIG_REF_NAME==xsdr_design_1_fifo_generator_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_clk_wiz_1_0 || ORIG_REF_NAME==xsdr_design_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_CyFX3_0_0/xsdr_design_1_CyFX3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_CyFX3_0_0 || ORIG_REF_NAME==xsdr_design_1_CyFX3_0_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_delay_32b_0_1/xsdr_design_1_delay_32b_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_delay_32b_0_1 || ORIG_REF_NAME==xsdr_design_1_delay_32b_0_1} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_1_0/xsdr_design_1_fifo_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_fifo_generator_1_0 || ORIG_REF_NAME==xsdr_design_1_fifo_generator_1_0} -quiet] -quiet

# IP: bd/xsdr_design_1/ip/xsdr_design_1_xsdr_ctrl_0_0/xsdr_design_1_xsdr_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xsdr_design_1_xsdr_ctrl_0_0 || ORIG_REF_NAME==xsdr_design_1_xsdr_ctrl_0_0} -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_clk_wiz_0_0 || ORIG_REF_NAME==xsdr_design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_clk_wiz_0_0 || ORIG_REF_NAME==xsdr_design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_clk_wiz_0_0 || ORIG_REF_NAME==xsdr_design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_fir_compiler_0_0 || ORIG_REF_NAME==xsdr_design_1_fir_compiler_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_fir_compiler_1_0 || ORIG_REF_NAME==xsdr_design_1_fir_compiler_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_0_0/xsdr_design_1_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_fifo_generator_0_0 || ORIG_REF_NAME==xsdr_design_1_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_0_0/xsdr_design_1_fifo_generator_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_fifo_generator_0_0 || ORIG_REF_NAME==xsdr_design_1_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_clk_wiz_1_0 || ORIG_REF_NAME==xsdr_design_1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_clk_wiz_1_0 || ORIG_REF_NAME==xsdr_design_1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_clk_wiz_1_0 || ORIG_REF_NAME==xsdr_design_1_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0_ooc.xdc

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_1_0/xsdr_design_1_fifo_generator_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_fifo_generator_1_0 || ORIG_REF_NAME==xsdr_design_1_fifo_generator_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_1_0/xsdr_design_1_fifo_generator_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xsdr_design_1_fifo_generator_1_0 || ORIG_REF_NAME==xsdr_design_1_fifo_generator_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_1_0/xsdr_design_1_fifo_generator_1_0_ooc.xdc

# XDC: bd/xsdr_design_1/xsdr_design_1_ooc.xdc
