# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Projects/xSDR/xSDR.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Projects/xSDR/xSDR.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Xilinx/Projects/xSDR/xSDR.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/new/ad9226_ibuf.v
  C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/new/dds_axis_data_to_sin_cos.v
  C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/new/iq32_to_fifo32.v
  C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/new/CyFX3.v
  C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/new/delay_32b.v
  C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/new/xsdr_ctrl.v
  C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/hdl/xsdr_design_1_wrapper.v
}
add_files C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/xsdr_design_1.bd
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_0_0/xsdr_design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_0_0/xsdr_design_1_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_0_0/xsdr_design_1_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0_late.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_clk_wiz_1_0/xsdr_design_1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_1_0/xsdr_design_1_fifo_generator_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_1_0/xsdr_design_1_fifo_generator_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/ip/xsdr_design_1_fifo_generator_1_0/xsdr_design_1_fifo_generator_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Xilinx/Projects/xSDR/xSDR.srcs/sources_1/bd/xsdr_design_1/xsdr_design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Projects/xSDR/xSDR.srcs/constrs_1/new/xsdr_constr_1.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Projects/xSDR/xSDR.srcs/constrs_1/new/xsdr_constr_1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xsdr_design_1_wrapper -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xsdr_design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xsdr_design_1_wrapper_utilization_synth.rpt -pb xsdr_design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
